version: '3.8'
services:
  db:
    image:
      postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  cache:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data
  web:
    build: .
    command: uwsgi --ini /code/config/uwsgi/uwsgi.ini
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - cache
      - db
  nginx:
    image: nginx:1.23.1
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
  daphe:
    build: .
    working_dir: /code/educa/
    command: ["daphne", "-u", "/code/educa/daphne.sock",
              "educa.asgi:application"]
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
